name: Test initMemory on ESP32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board:
          - esp32:esp32:esp32dev
          - esp32:esp32:esp32wrover
          - esp32:esp32:esp32s3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1
        with:
          version: latest

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile examples for ${{ matrix.board }}
        run: |
          for sketch in $(find examples -name '*.ino'); do
            echo "Compiling $sketch for ${{ matrix.board }}"
            arduino-cli compile --fqbn ${{ matrix.board }} "$sketch"
          done
